<?php

use Illuminate\Database\Seeder;

class BusinessSchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('business_schools')->insert([

                [ 'id'=>'1','name' => 'City University of Science & Technology Peshawar', 'status' => 'active'],
                ['id'=>'2','name' => 'Abasyn University Peshawar', 'status' => 'active'],
                ['id'=>'3','name' => 'Capital University of Science & Technology', 'status' => 'active'],
                ['id'=>'4','name' => 'Air University, Islamabad', 'status' => 'active'],
                ['id'=>'5','name' => 'Allama Iqbal Open University, Islamabad (AIOU)', 'status' => 'active'],
                ['id'=>'6','name' => 'Bahria University, Islamabad', 'status' => 'active'],
                ['id'=>'7','name' => 'COMSATS University (Formerly COMSATS Institute of Information Technology), Islamabad', 'status' => 'active'],
                ['id'=>'8','name' => 'Dawood University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['id'=>'9','name' => 'Federal Urdu University of Arts, Sciences & Technology, Islamabad', 'status' => 'active'],
                ['id'=>'10','name' => 'Institute of Space Technology (IST), Islamabad', 'status' => 'active'],
                ['id'=>'11','name' => 'International Islamic University, Islamabad', 'status' => 'active'],
                ['id'=>'12','name' => 'Karakurum International University, Gilgit, Gilgit Baltistan', 'status' => 'active'],
                ['id'=>'13','name' => 'National College of Arts, Lahore', 'status' => 'active'],
                ['id'=>'14','name' => 'National Defense University, Islamabad', 'status' => 'active'],
                ['id'=>'15','name' => 'National Textile University, Faisalabad', 'status' => 'active'],
                ['id'=>'16','name' => 'National University of Modern Languages, Islamabad', 'status' => 'active'],
                ['id'=>'17','name' => 'National University of Sciences & Technology, Islamabad', 'status' => 'active'],
                ['id'=>'18','name' => 'NFC Institute of Engineering & Technology, Multan', 'status' => 'active'],
                ['id'=>'19','name' => 'Pakistan Institute of Development Economics (PIDE), Islamabad', 'status' => 'active'],
                ['id'=>'20','name' => 'Pakistan Institute of Engineering & Applied Sciences, Islamabad (PIEAS)', 'status' => 'active'],
                ['id'=>'21','name' => 'Pakistan Institute of Fashion and Design, Lahore', 'status' => 'active'],
                ['id'=>'22','name' => 'Pakistan Military Academy (PMA), Abbottabad', 'status' => 'active'],
                ['id'=>'23','name' => 'Pakistan Naval Academy, Karachi', 'status' => 'active'],
                ['id'=>'24','name' => 'Shaheed Zulfiqar Ali Bhutto Medical University, Islamabad', 'status' => 'active'],
                ['id'=>'25','name' => 'Quaid-i-Azam University, Islamabad', 'status' => 'active'],
                ['id'=>'26','name' => 'FATA University, Dara Adam Khel, FR Kohat', 'status' => 'active'],
                ['id'=>'27','name' => 'Virtual University of Pakistan, Lahore', 'status' => 'active'],
                ['id'=>'28','name' => 'National University of Medical Sciences, Rawalpindi', 'status' => 'active'],
                ['id'=>'29','name' => 'University of Baltistan, Skardu', 'status' => 'active'],
                ['id'=>'30','name' => 'National University of Technology (NUTECH), Islamabad', 'status' => 'active'],
                ['id'=>'31','name' => 'Bahauddin Zakariya University, Multan', 'status' => 'active'],
                ['id'=>'32','name' => 'Fatima Jinnah Women University, Rawalpindi', 'status' => 'active'],
                ['id'=>'33','name' => 'Government College University, Faisalabad', 'status' => 'active'],
                ['id'=>'34','name' => 'Government College University, Lahore', 'status' => 'active'],
                ['id'=>'35','name' => 'Government College for Women University, Faisalabad', 'status' => 'active'],
                ['id'=>'36','name' => 'Ghazi University, Dera Ghazi Khan', 'status' => 'active'],
                ['id'=>'37','name' => 'Government College for Women University, Sialkot', 'status' => 'active'],
                ['id'=>'38','name' => 'Government Sadiq College Women University, Bahawalpur', 'status' => 'active'],
                ['id'=>'39','name' => 'Islamia University, Bahawalpur', 'status' => 'active'],
                ['id'=>'40','name' => 'Information Technology University of the Punjab, Lahore', 'status' => 'active'],
                ['id'=>'41','name' => 'King Edward Medical University, Lahore', 'status' => 'active'],
                ['id'=>'42','name' => 'Kinnaird College for Women, Lahore', 'status' => 'active'],
                ['id'=>'43','name' => 'Khawaja Freed University of Engineering & Information Technology, Rahim Yar Khan', 'status' => 'active'],
                ['id'=>'44','name' => 'Lahore College for Women University, Lahore', 'status' => 'active'],
                ['id'=>'45','name' => 'Muhammad Nawaz Shareef University of Agriculture, Multan', 'status' => 'active'],
                ['id'=>'46','name' => 'Nishtar Medical University, Multan', 'status' => 'active'],
                ['id'=>'47','name' => 'Pir Mehr Ali Shah Arid Agriculture University (Formerly University of Arid Agriculture), Rawalpindi', 'status' => 'active'],
                ['id'=>'48','name' => 'Rawalpindi Medical University, Rawalpindi', 'status' => 'active'],
                ['id'=>'49','name' => 'University of Agriculture, Faisalabad', 'status' => 'active'],
                ['id'=>'50','name' => 'University of Education, Lahore', 'status' => 'active'],
                ['id'=>'51','name' => 'University of Engineering & Technology, Lahore', 'status' => 'active'],
                ['id'=>'52','name' => 'University of Engineering & Technology, Taxila', 'status' => 'active'],
                ['id'=>'53','name' => 'University of Gujrat, Gujrat', 'status' => 'active'],
                ['id'=>'54','name' => 'University of Health Sciences, Lahore', 'status' => 'active'],
                ['id'=>'55','name' => 'University of Sargodha, Sargodha', 'status' => 'active'],
                ['id'=>'56','name' => 'University of the Punjab, Lahore', 'status' => 'active'],
                ['id'=>'57','name' => 'University of Veterinary & Animal Sciences, Lahore', 'status' => 'active'],
                ['id'=>'58','name' => 'The Women University, Multan', 'status' => 'active'],
                ['id'=>'59','name' => 'Muhammad Nawaz Sharif University of  Engineering & Technology, Multan', 'status' => 'active'],
                ['id'=>'61','name' => 'Fatima Jinnah Medical University, Lahore', 'status' => 'active'],
                ['id'=>'62','name' => 'Punjab Tianjin University of Technology, Lahore', 'status' => 'active'],
                ['id'=>'63','name' => 'University of Okara, Okara', 'status' => 'active'],
                ['id'=>'64','name' => 'Faisalabad Medical University, Faisalabad', 'status' => 'active'],
                ['id'=>'65','name' => 'University of Sahiwal, Sahiwal', 'status' => 'active'],
                ['id'=>'66','name' => 'Cholistan University of Veterinary and Animal Sciences, Bahawalpur', 'status' => 'active'],
                ['id'=>'67','name' => 'University of Narowal, Narowa', 'status' => 'active'],
                ['id'=>'68','name' => 'Benazir Bhutto Shaheed University Lyari, Karachi', 'status' => 'active'],
                ['id'=>'69','name' => 'DOW University of Health Sciences, Karachi ', 'status' => 'active'],
                ['id'=>'70','name' => 'Gambat Institute of Medical Sciences, Khairpur', 'status' => 'active'],
                ['id'=>'71','name' => 'Institute of Business Administration, Karachi', 'status' => 'active'],
                ['id'=>'72','name' => 'Jinnah Sindh Medical University', 'status' => 'active'],
                ['id'=>'73','name' => 'Liaquat University of Medical and Health Sciences, Jamshoro', 'status' => 'active'],
                ['id'=>'74','name' => 'Mehran University of Engineering & Technology, Jamshoro', 'status' => 'active'],
                 ['id'=>'75','name' => 'NED University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['id'=>'76','name' => 'Peoples University of Medical and Health Sciences for Women, Nawabshah (Shaheed Benazirabad)', 'status' => 'active'],
                ['id'=>'77','name' => 'Quaid-e-Awam University of Engineering, Sciences & Technology, Nawabshah', 'status' => 'active'],
                ['id'=>'78','name' => 'NawabshahShah Abdul Latif University, KhairpurShaheed', 'status' => 'active'],
                ['id'=>'79','name' => 'Shaheed Mohtarma Benazir Bhutto Medical University, Larkana', 'status' => 'active'],
                ['id'=>'80','name' => 'Sindh Agriculture University, Tandojam', 'status' => 'active'],
                ['id'=>'81','name' => 'Sukkur Institute of Business Administration, Sukkur ', 'status' => 'active'],
                ['id'=>'82','name' => 'Sindh Madressatul Islam University (SMIU), Karachi', 'status' => 'active'],
                ['id'=>'83','name' => 'Shaheed Benazir Bhutto University, Shaheed Benazirabad', 'status' => 'active'],
                ['id'=>'84','name' => 'Shaheed Zulfiqar Ali Bhutto University of Law, Karachi', 'status' => 'active'],
                ['id'=>'85','name' => 'University of Karachi, Karachi', 'status' => 'active'],
                ['id'=>'86','name' => 'University of Sindh, Jamshoro', 'status' => 'active'],
                ['id'=>'87','name' => 'Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur Mirs', 'status' => 'active'],
                ['id'=>'88','name' => 'University of Sufism and Modern Sciences, Bhitshah', 'status' => 'active'],
                ['id'=>'89','name' => 'Government College University, Hyderabad', 'status' => 'active'],
                ['id'=>'90','name' => 'The Shaikh Ayaz University, Shikarpur', 'status' => 'active'],
                ['id'=>'91','name' => 'Abdul Wali Khan University, Mardan', 'status' => 'active'],
                ['id'=>'92','name' => 'Abbottabd University of Science and Technology, Abbottabad', 'status' => 'active'],
                 ['id'=>'93','name' => 'Bacha Khan University, Charsadda', 'status' => 'active'],
                ['id'=>'94','name' => 'Shaheed Benazir Bhutto Women University (formerly Frontier Women University), Peshawar', 'status' => 'active'],
                ['id'=>'95','name' => 'Gomal University, Dera Ismail Khan', 'status' => 'active'],
                ['id'=>'96','name' => 'Hazara University, Dodhial, Mansehra', 'status' => 'active'],
                ['id'=>'97','name' => 'Institute of Management Science (IMS), Peshawar', 'status' => 'active'],
                ['id'=>'98','name' => 'Islamia College University, Peshawar', 'status' => 'active'],
                ['id'=>'99','name' => 'Khyber Medical University, Peshawar ', 'status' => 'active'],
                ['id'=>'100','name' => 'Kohat University of Science and Technology, Kohat', 'status' => 'active'],
                ['id'=>'101','name' => 'Khushal Khan Khattak University, Karak', 'status' => 'active'],
                ['id'=>'102','name' => 'Khyber Pakhtunkhwa Agricultural University, Peshawar', 'status' => 'active'],
                ['id'=>'103','name' => 'University of Engineering & Technology, Peshawar', 'status' => 'active'],
                ['id'=>'104','name' => 'Shaheed Benazir Bhutto University, Sheringal, Dir', 'status' => 'active'],
                ['id'=>'105','name' => 'University of Malakand, Chakdara, Dir, Malakand', 'status' => 'active'],
                ['id'=>'106','name' => 'University of Peshawar, Peshawar', 'status' => 'active'],
                ['id'=>'107','name' => 'University of Science & Technology, Bannu', 'status' => 'active'],
                ['id'=>'108','name' => 'University of Swat, Swat', 'status' => 'active'],
                ['id'=>'109','name' => 'University of Haripur, Haripur', 'status' => 'active'],
                ['id'=>'110','name' => 'University of Swabi', 'status' => 'active'],
                ['id'=>'111','name' => 'University of Swabi for Women, Swabi', 'status' => 'active'],
                ['id'=>'112','name' => 'Shuhada-e-Army Public School, University of Technology, Nowshera', 'status' => 'active'],
                ['id'=>'113','name' => 'Women University, Mardan', 'status' => 'active'],
                ['id'=>'114','name' => 'University of Engineering & Technology, Mardan', 'status' => 'active'],
                ['id'=>'115','name' => 'University of Lakki Marwat', 'status' => 'active'],
                ['id'=>'116','name' => 'University of Buner', 'status' => 'active'],
                ['id'=>'117','name' => 'University of Chitral', 'status' => 'active'],
                ['id'=>'118','name' => 'Balochistan University of Engineering & Technology, Khuzdar', 'status' => 'active'],
                ['id'=>'119','name' => 'Balochistan University of Information Technology & Management Sciences, Quetta', 'status' => 'active'],
                ['id'=>'120','name' => 'Lasbela University of Agriculture, Water and Marine Sciences', 'status' => 'active'],
                ['id'=>'121','name' => 'Sardar Bahadur Khan Women University, Quetta', 'status' => 'active'],
                ['id'=>'122','name' => 'University of Balochistan, Quetta', 'status' => 'active'],
                ['id'=>'123','name' => 'University of Turbat, Turbat', 'status' => 'active'],
                ['id'=>'124','name' => 'University of Loralai, Loralai', 'status' => 'active'],
                ['id'=>'125','name' => 'Bolan University of Medical and Health Sciences, Quetta', 'status' => 'active'],
                ['id'=>'126','name' => 'Mirpur University of Science and Technology (MUST), AJ&K', 'status' => 'active'],
                ['id'=>'127','name' => 'University of Azad Jammu & Kashmir, Muzaffarabad, Azad Kashmir, Muzaffarabad', 'status' => 'active'],
                ['id'=>'128','name' => 'University of Poonch, Rawalakot', 'status' => 'active'],
                ['id'=>'129','name' => 'Women University of Azad Jammu and Kashmir, Bagh-AJ&K', 'status' => 'active'],
                ['id'=>'130','name' => 'University of Management Sciences and Information Technology, Kotli', 'status' => 'active'],
                ['id'=>'131','name' => 'Aga Khan University, Karachi', 'status' => 'active'],
                ['id'=>'132','name' => 'Foundation University, Islamabad', 'status' => 'active'],
                ['id'=>'133','name' => 'Lahore University of Management Sciences (LUMS), Lahore
', 'status' => 'active'],
                ['id'=>'134','name' => 'Muslim Youth University, Islamabad', 'status' => 'active'],
                ['id'=>'135','name' => 'National University of Computer and Emerging Sciences, Islamabad', 'status' => 'active'],
                ['id'=>'136','name' => 'Riphah International University, Islamabad', 'status' => 'active'],
                ['id'=>'137','name' => 'Shifa Tameer-e-Millat University, Islamabad
', 'status' => 'active'],
                ['id'=>'138','name' => 'Capital University of Science and Technology, Islamabad', 'status' => 'active'],
                ['id'=>'139','name' => 'Institute of Art and Culture, Lahore', 'status' => 'active'],
                ['id'=>'140','name' => 'Sir Syed CASE Institute of Technology, Islamabad', 'status' => 'active'],
                ['id'=>'141','name' => 'Ali Institute of Education, Lahore', 'status' => 'active'],
                ['id'=>'142','name' => 'Beaconhouse National University, Lahore', 'status' => 'active'],
                ['id'=>'143','name' => 'Forman Christian College, Lahore (university status)', 'status' => 'active'],
                ['id'=>'144','name' => 'Global Institute, Lahore', 'status' => 'active'],
                ['id'=>'145','name' => 'Hajvery University, Lahore', 'status' => 'active'],
                ['id'=>'146','name' => 'HITEC University, Taxila', 'status' => 'active'],
                ['id'=>'147','name' => 'Imperial College of Business Studies, Lahore', 'status' => 'active'],
                ['id'=>'148','name' => 'Institute of Management Sciences, Lahore', 'status' => 'active'],
                ['id'=>'149','name' => 'Institute of Southern Punjab, Multan', 'status' => 'active'],
                ['id'=>'150','name' => 'Lahore Leads University, Lahore', 'status' => 'active'],
                ['id'=>'151','name' => 'Lahore School of Economics, Lahore', 'status' => 'active'],
                ['id'=>'152','name' => 'Lahore Garrison University, Lahore', 'status' => 'active'],
                ['id'=>'153','name' => 'Minhaj University, Lahore ', 'status' => 'active'],
                ['id'=>'154','name' => 'National College of Business Administration & Economics, Lahore', 'status' => 'active'],
                ['id'=>'155','name' => 'Nur International University, Lahore', 'status' => 'active'],
                ['id'=>'156','name' => 'Qarshi University ', 'status' => 'active'],
                ['id'=>'157','name' => 'The GIFT University, Gujranwala', 'status' => 'active'],
                ['id'=>'158','name' => 'The Superior College, Lahore ', 'status' => 'active'],
                ['id'=>'159','name' => 'The University of Faisalabad, Faisalabad', 'status' => 'active'],
                ['id'=>'160','name' => 'University of Central Punjab, Lahore', 'status' => 'active'],
                ['id'=>'161','name' => 'University of Lahore, Lahore', 'status' => 'active'],
                ['id'=>'162','name' => 'University of Management & Technology, Lahore', 'status' => 'active'],
                ['id'=>'163','name' => 'University of South Asia, Lahore', 'status' => 'active'],
                ['id'=>'164','name' => 'University of Wah, Wah', 'status' => 'active'],
                ['id'=>'165','name' => 'University of Sialkot, Sialkot', 'status' => 'active'],
                ['id'=>'166','name' => 'NAMAL Institute, Mianwali ', 'status' => 'active'],
                ['id'=>'167','name' => 'Baqai Medical University, Karachi', 'status' => 'active'],
                ['id'=>'168','name' => 'Barrett Hodgson University, Karachi', 'status' => 'active'],
                ['id'=>'169','name' => 'Commecs Institute of Business & Emerging Sciences, Karachi', 'status' => 'active'],
                ['id'=>'170','name' => 'Dadabhoy Institute of Higher Education,Karachi', 'status' => 'active'],
                ['id'=>'171','name' => 'DHA Suffa University, Karachi', 'status' => 'active'],
                ['id'=>'172','name' => 'Greenwich University, Karachi', 'status' => 'active'],
                ['id'=>'173','name' => 'Hamdard University, Karachi', 'status' => 'active'],
                ['id'=>'174','name' => 'Habib University, Karachi', 'status' => 'active'],
                ['id'=>'175','name' => 'Indus University, Karachi', 'status' => 'active'],
                ['id'=>'176','name' => 'Indus Valley School of Art and Architecture, Karachi', 'status' => 'active'],
                ['id'=>'177','name' => 'Institute of Business Management, Karachi', 'status' => 'active'],
                ['id'=>'178','name' => 'ILMA University (Formerly Institute of Business and Technology), Karachi', 'status' => 'active'],
                ['id'=>'179','name' => 'Iqra University, Karachi', 'status' => 'active'],
                ['id'=>'180','name' => 'Isra University, Hyderabad', 'status' => 'active'],
                ['id'=>'181','name' => 'Jinnah University for Women, Karachi', 'status' => 'active'],
                ['id'=>'182','name' => 'Karachi Institute of Economics & Technology, Karachi', 'status' => 'active'],
                ['id'=>'183','name' => 'KASB Institute of Technology, Karachi', 'status' => 'active'],
                ['id'=>'184','name' => 'Karachi School for Business & Leadership, Karachi', 'status' => 'active'],
<<<<<<< HEAD
                ['id'=>'185','name' => 'Preston University, Karachi
', 'status' => 'active'],
                ['id'=>'186','name' => 'Shaheed Zulfikar Ali Bhutto Institute of Science & Technology (SZABIST), Karachi
', 'status' => 'active'],
                ['id'=>'187','name' => 'Shaheed Benazir Bhutto City University, Karachi
', 'status' => 'active'],
                ['id'=>'188','name' => 'Sir Syed University of Engineering & Technology, Karachi
', 'status' => 'active'],
=======
                ['id'=>'185','name' => '', 'status' => 'active'],
                ['id'=>'186','name' => '', 'status' => 'active'],
                ['id'=>'187','name' => '', 'status' => 'active'],
                ['id'=>'188','name' => '', 'status' => 'active'],
>>>>>>> 72e13fb02c223442c2c577d15987c897ec6f5497
                ['id'=>'189','name' => 'Muhammad Ali Jinnah University, Karachi', 'status' => 'active'],
                ['id'=>'190','name' => 'Newport Institute of Communications & Economics, Karachi', 'status' => 'active'],
                ['id'=>'191','name' => 'Preston Institute of Management, Science and Technology, Karachi', 'status' => 'active'],
                ['id'=>'192','name' => 'Preston University, Karachi', 'status' => 'active'],
                ['id'=>'193','name' => 'Shaheed Zulfikar Ali Bhutto Institute of Science & Technology (SZABIST), Karachi', 'status' => 'active'],
                ['id'=>'194','name' => 'Shaheed Benazir Bhutto City University, Karachi', 'status' => 'active'],
                ['id'=>'195','name' => 'Sir Syed University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['id'=>'196','name' => 'Sindh Institute of Medical Sciences, Karachi', 'status' => 'active'],
                ['id'=>'197','name' => 'Sindh Institute of Management and Technology, Karachi', 'status' => 'active'],
                ['id'=>'198','name' => 'Textile Institute of Pakistan, Karachi', 'status' => 'active'],
                ['id'=>'199','name' => 'Nazeer Hussian University, Karachi', 'status' => 'active'],
                ['id'=>'200','name' => 'Zia-ud-Din University, Karachi', 'status' => 'active'],
                ['id'=>'201','name' => 'Shaheed Benazir Bhutto Dewan University, Karachi', 'status' => 'active'],
                ['id'=>'202','name' => 'Emaan Institute of Management & Sciences, Karachi', 'status' => 'active'],
                ['id'=>'203','name' => 'Abasyn University, Peshawar ', 'status' => 'active'],
                ['id'=>'204','name' => 'CECOS University of Information Technology and Emerging Sciences, Peshawar', 'status' => 'active'],
                ['id'=>'205','name' => 'City University of Science and Information Technology, Peshawar', 'status' => 'active'],
                ['id'=>'206','name' => 'Gandhara University, Peshawar', 'status' => 'active'],
                ['id'=>'207','name' => 'Ghulam Ishaq Khan Institute of Engineering Sciences & Technology, Topi', 'status' => 'active'],
                ['id'=>'208','name' => 'Iqra National University, Peshawar', 'status' => 'active'],
                ['id'=>'209','name' => 'Northern University, Nowshera', 'status' => 'active'],
                ['id'=>'210','name' => 'Preston University, Kohat', 'status' => 'active'],
                ['id'=>'211','name' => 'Qurtaba University of Science and Information Technology, Dera Ismail Khan', 'status' => 'active'],
                ['id'=>'212','name' => 'Sarhad University of Science and Information Technology, Peshawar ', 'status' => 'active'],
                ['id'=>'213','name' => 'BRAINS Institute, Peshawar', 'status' => 'active'],
                ['id'=>'214','name' => 'Al-Hamd Islamic University, Quetta', 'status' => 'active'],
                ['id'=>'215','name' => 'Al-Khair University, AJ&K (Banned for new intake of students w.e.f  Fall, 2016 in all subjects and levels)
', 'status' => 'active'],
                ['id'=>'216','name' => 'Mohi-ud-Din Islamic University, AJK ', 'status' => 'active'],
                ['id'=> '217 ','name' => 'Shaheed Benazir Bhutto University of Veterinary And Animal Sciences, Sakrand', 'status' => 'active'],

            ]
        );
    }
}
