<?php

use Illuminate\Database\Seeder;

class BusinessSchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('business_schools')->insert([

                ['name' => 'City University of Science & Technology Peshawar', 'status' => 'active'],
                ['name' => 'Abasyn University Peshawar', 'status' => 'active'],
                ['name' => 'Capital University of Science & Technology', 'status' => 'active'],

                ['name' => 'Air University, Islamabad', 'status' => 'active'],
                ['name' => 'Allama Iqbal Open University, Islamabad (AIOU)', 'status' => 'active'],
                ['name' => 'Bahria University, Islamabad', 'status' => 'active'],
                ['name' => 'COMSATS University (Formerly COMSATS Institute of Information Technology), Islamabad', 'status' => 'active'],
                ['name' => 'Dawood University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['name' => 'Federal Urdu University of Arts, Sciences & Technology, Islamabad', 'status' => 'active'],
                ['name' => 'Institute of Space Technology (IST), Islamabad', 'status' => 'active'],
                ['name' => 'International Islamic University, Islamabad', 'status' => 'active'],
                ['name' => 'Karakurum International University, Gilgit, Gilgit Baltistan', 'status' => 'active'],
                ['name' => 'National College of Arts, Lahore', 'status' => 'active'],
                ['name' => 'National Defense University, Islamabad', 'status' => 'active'],
                ['name' => 'National Textile University, Faisalabad', 'status' => 'active'],
                ['name' => 'National University of Modern Languages, Islamabad', 'status' => 'active'],
                ['name' => 'National University of Sciences & Technology, Islamabad', 'status' => 'active'],
                ['name' => 'NFC Institute of Engineering & Technology, Multan', 'status' => 'active'],
                ['name' => 'Pakistan Institute of Development Economics (PIDE), Islamabad', 'status' => 'active'],
                ['name' => 'Pakistan Institute of Engineering & Applied Sciences, Islamabad (PIEAS)', 'status' => 'active'],
                ['name' => 'Pakistan Institute of Fashion and Design, Lahore', 'status' => 'active'],
                ['name' => 'Pakistan Military Academy (PMA), Abbottabad', 'status' => 'active'],
                ['name' => 'Pakistan Naval Academy, Karachi', 'status' => 'active'],
                ['name' => 'Shaheed Zulfiqar Ali Bhutto Medical University, Islamabad', 'status' => 'active'],
                ['name' => 'Quaid-i-Azam University, Islamabad', 'status' => 'active'],
                ['name' => 'FATA University, Dara Adam Khel, FR Kohat', 'status' => 'active'],
                ['name' => 'Virtual University of Pakistan, Lahore', 'status' => 'active'],
                ['name' => 'National University of Medical Sciences, Rawalpindi', 'status' => 'active'],
                ['name' => 'University of Baltistan, Skardu', 'status' => 'active'],
                ['name' => 'National University of Technology (NUTECH), Islamabad', 'status' => 'active'],
                ['name' => 'Bahauddin Zakariya University, Multan', 'status' => 'active'],
                ['name' => 'Fatima Jinnah Women University, Rawalpindi', 'status' => 'active'],
                ['name' => 'Government College University, Faisalabad', 'status' => 'active'],
                ['name' => 'Government College University, Lahore', 'status' => 'active'],
                ['name' => 'Government College for Women University, Faisalabad', 'status' => 'active'],
                ['name' => 'Ghazi University, Dera Ghazi Khan', 'status' => 'active'],
                ['name' => 'Government College for Women University, Sialkot', 'status' => 'active'],
                ['name' => 'Government Sadiq College Women University, Bahawalpur', 'status' => 'active'],
                ['name' => 'Islamia University, Bahawalpur', 'status' => 'active'],
                ['name' => 'Information Technology University of the Punjab, Lahore', 'status' => 'active'],
                ['name' => 'King Edward Medical University, Lahore', 'status' => 'active'],
                ['name' => 'Kinnaird College for Women, Lahore', 'status' => 'active'],
                ['name' => 'Khawaja Freed University of Engineering & Information Technology, Rahim Yar Khan', 'status' => 'active'],
                ['name' => 'Lahore College for Women University, Lahore', 'status' => 'active'],
                ['name' => 'Muhammad Nawaz Shareef University of Agriculture, Multan', 'status' => 'active'],
                ['name' => 'Nishtar Medical University, Multan', 'status' => 'active'],
                ['name' => 'Pir Mehr Ali Shah Arid Agriculture University (Formerly University of Arid Agriculture), Rawalpindi', 'status' => 'active'],
                ['name' => 'Rawalpindi Medical University, Rawalpindi', 'status' => 'active'],
                ['name' => 'University of Agriculture, Faisalabad', 'status' => 'active'],
                ['name' => 'University of Education, Lahore', 'status' => 'active'],
                ['name' => 'University of Engineering & Technology, Lahore', 'status' => 'active'],
                ['name' => 'University of Engineering & Technology, Taxila', 'status' => 'active'],
                ['name' => 'University of Gujrat, Gujrat', 'status' => 'active'],
                ['name' => 'University of Health Sciences, Lahore', 'status' => 'active'],
                ['name' => 'University of Sargodha, Sargodha', 'status' => 'active'],
                ['name' => 'University of the Punjab, Lahore', 'status' => 'active'],
                ['name' => 'University of Veterinary & Animal Sciences, Lahore', 'status' => 'active'],
                ['name' => 'The Women University, Multan', 'status' => 'active'],
                ['name' => 'Muhammad Nawaz Sharif University of  Engineering & Technology, Multan', 'status' => 'active'],
                ['name' => 'Fatima Jinnah Medical University, Lahore', 'status' => 'active'],
                ['name' => 'Punjab Tianjin University of Technology, Lahore', 'status' => 'active'],
                ['name' => 'University of Okara, Okara', 'status' => 'active'],
                ['name' => 'Faisalabad Medical University, Faisalabad', 'status' => 'active'],
                ['name' => 'University of Sahiwal, Sahiwal', 'status' => 'active'],
                ['name' => 'Cholistan University of Veterinary and Animal Sciences, Bahawalpur', 'status' => 'active'],
                ['name' => 'University of Narowal, Narowa', 'status' => 'active'],
                ['name' => 'Benazir Bhutto Shaheed University Lyari, Karachi', 'status' => 'active'],
                ['name' => 'DOW University of Health Sciences, Karachi ', 'status' => 'active'],
                ['name' => 'Gambat Institute of Medical Sciences, Khairpur', 'status' => 'active'],
                ['name' => 'Institute of Business Administration, Karachi', 'status' => 'active'],
                ['name' => 'Jinnah Sindh Medical University', 'status' => 'active'],
                ['name' => 'Liaquat University of Medical and Health Sciences, Jamshoro', 'status' => 'active'],
                ['name' => 'Mehran University of Engineering & Technology, Jamshoro', 'status' => 'active'],
                 ['name' => 'NED University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['name' => 'Peoples University of Medical and Health Sciences for Women, Nawabshah (Shaheed Benazirabad)', 'status' => 'active'],
                ['name' => 'Quaid-e-Awam University of Engineering, Sciences & Technology, Nawabshah', 'status' => 'active'],
                ['name' => 'NawabshahShah Abdul Latif University, KhairpurShaheed', 'status' => 'active'],
                ['name' => 'Shaheed Mohtarma Benazir Bhutto Medical University, Larkana', 'status' => 'active'],
                ['name' => 'Sindh Agriculture University, Tandojam', 'status' => 'active'],
                ['name' => 'Sukkur Institute of Business Administration, Sukkur ', 'status' => 'active'],
                ['name' => 'Sindh Madressatul Islam University (SMIU), Karachi', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto University, Shaheed Benazirabad', 'status' => 'active'],
                ['name' => 'Shaheed Zulfiqar Ali Bhutto University of Law, Karachi', 'status' => 'active'],
                ['name' => 'University of Karachi, Karachi', 'status' => 'active'],
                ['name' => 'University of Sindh, Jamshoro', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto University of Veterinary And Animal Sciences, Sakrand', 'status' => 'active'],
                ['name' => 'Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur Mirs', 'status' => 'active'],
                ['name' => 'University of Sufism and Modern Sciences, Bhitshah', 'status' => 'active'],
                ['name' => 'Government College University, Hyderabad', 'status' => 'active'],
                ['name' => 'The Shaikh Ayaz University, Shikarpur', 'status' => 'active'],
                ['name' => 'Abdul Wali Khan University, Mardan', 'status' => 'active'],
                ['name' => 'Abbottabd University of Science and Technology, Abbottabad', 'status' => 'active'],
                 ['name' => 'Bacha Khan University, Charsadda', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto Women University (formerly Frontier Women University), Peshawar', 'status' => 'active'],
                ['name' => 'Gomal University, Dera Ismail Khan', 'status' => 'active'],
                ['name' => 'Hazara University, Dodhial, Mansehra', 'status' => 'active'],
                ['name' => 'Institute of Management Science (IMS), Peshawar', 'status' => 'active'],
                ['name' => 'Islamia College University, Peshawar', 'status' => 'active'],
                ['name' => 'Khyber Medical University, Peshawar ', 'status' => 'active'],
                ['name' => 'Kohat University of Science and Technology, Kohat', 'status' => 'active'],
                ['name' => 'Khushal Khan Khattak University, Karak', 'status' => 'active'],
                ['name' => 'Khyber Pakhtunkhwa Agricultural University, Peshawar', 'status' => 'active'],
                ['name' => 'University of Engineering & Technology, Peshawar', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto University, Sheringal, Dir', 'status' => 'active'],
                ['name' => 'University of Malakand, Chakdara, Dir, Malakand', 'status' => 'active'],
                ['name' => 'University of Peshawar, Peshawar', 'status' => 'active'],
                ['name' => 'University of Science & Technology, Bannu', 'status' => 'active'],
                ['name' => 'University of Swat, Swat', 'status' => 'active'],
                ['name' => 'University of Haripur, Haripur', 'status' => 'active'],
                ['name' => 'University of Swabi', 'status' => 'active'],
                ['name' => 'University of Swabi for Women, Swabi', 'status' => 'active'],
                ['name' => 'Shuhada-e-Army Public School, University of Technology, Nowshera', 'status' => 'active'],
                ['name' => 'Women University, Mardan', 'status' => 'active'],
                ['name' => 'University of Engineering & Technology, Mardan', 'status' => 'active'],
                ['name' => 'University of Lakki Marwat', 'status' => 'active'],
                ['name' => 'University of Buner', 'status' => 'active'],
                ['name' => 'University of Chitral', 'status' => 'active'],
                ['name' => 'Balochistan University of Engineering & Technology, Khuzdar', 'status' => 'active'],
                ['name' => 'Balochistan University of Information Technology & Management Sciences, Quetta', 'status' => 'active'],
                ['name' => 'Lasbela University of Agriculture, Water and Marine Sciences', 'status' => 'active'],
                ['name' => 'Sardar Bahadur Khan Women University, Quetta', 'status' => 'active'],
                ['name' => 'University of Balochistan, Quetta', 'status' => 'active'],
                ['name' => 'University of Turbat, Turbat', 'status' => 'active'],
                ['name' => 'University of Loralai, Loralai', 'status' => 'active'],
                ['name' => 'Bolan University of Medical and Health Sciences, Quetta', 'status' => 'active'],
                ['name' => 'Mirpur University of Science and Technology (MUST), AJ&K', 'status' => 'active'],
                ['name' => 'University of Azad Jammu & Kashmir, Muzaffarabad, Azad Kashmir, Muzaffarabad', 'status' => 'active'],
                ['name' => 'University of Poonch, Rawalakot', 'status' => 'active'],
                ['name' => 'Women University of Azad Jammu and Kashmir, Bagh-AJ&K', 'status' => 'active'],
                ['name' => 'University of Management Sciences and Information Technology, Kotli', 'status' => 'active'],
                ['name' => 'Aga Khan University, Karachi', 'status' => 'active'],
                ['name' => 'Foundation University, Islamabad', 'status' => 'active'],
                ['name' => 'Lahore University of Management Sciences (LUMS), Lahore
', 'status' => 'active'],
                ['name' => 'Muslim Youth University, Islamabad', 'status' => 'active'],
                ['name' => 'National University of Computer and Emerging Sciences, Islamabad', 'status' => 'active'],
                ['name' => 'Riphah International University, Islamabad', 'status' => 'active'],
                ['name' => 'Shifa Tameer-e-Millat University, Islamabad
', 'status' => 'active'],
                ['name' => 'Capital University of Science and Technology, Islamabad', 'status' => 'active'],
                ['name' => 'Institute of Art and Culture, Lahore', 'status' => 'active'],
                ['name' => 'Sir Syed CASE Institute of Technology, Islamabad', 'status' => 'active'],
                ['name' => 'Ali Institute of Education, Lahore', 'status' => 'active'],
                ['name' => 'Beaconhouse National University, Lahore', 'status' => 'active'],
                ['name' => 'Forman Christian College, Lahore (university status)', 'status' => 'active'],
                ['name' => 'Global Institute, Lahore', 'status' => 'active'],
                ['name' => 'Hajvery University, Lahore', 'status' => 'active'],
                ['name' => 'HITEC University, Taxila', 'status' => 'active'],
                ['name' => 'Imperial College of Business Studies, Lahore', 'status' => 'active'],
                ['name' => 'Institute of Management Sciences, Lahore', 'status' => 'active'],
                ['name' => 'Institute of Southern Punjab, Multan', 'status' => 'active'],
                ['name' => 'Lahore Leads University, Lahore', 'status' => 'active'],
                ['name' => 'Lahore School of Economics, Lahore', 'status' => 'active'],
                ['name' => 'Lahore Garrison University, Lahore', 'status' => 'active'],
                ['name' => 'Minhaj University, Lahore ', 'status' => 'active'],
                ['name' => 'National College of Business Administration & Economics, Lahore', 'status' => 'active'],
                ['name' => 'Nur International University, Lahore', 'status' => 'active'],
                ['name' => 'Qarshi University ', 'status' => 'active'],
                ['name' => 'The GIFT University, Gujranwala', 'status' => 'active'],
                ['name' => 'The Superior College, Lahore ', 'status' => 'active'],
                ['name' => 'The University of Faisalabad, Faisalabad', 'status' => 'active'],
                ['name' => 'University of Central Punjab, Lahore', 'status' => 'active'],
                ['name' => 'University of Lahore, Lahore', 'status' => 'active'],
                ['name' => 'University of Management & Technology, Lahore', 'status' => 'active'],
                ['name' => 'University of South Asia, Lahore', 'status' => 'active'],
                ['name' => 'University of Wah, Wah', 'status' => 'active'],
                ['name' => 'University of Sialkot, Sialkot', 'status' => 'active'],
                ['name' => 'NAMAL Institute, Mianwali ', 'status' => 'active'],
                ['name' => 'Baqai Medical University, Karachi', 'status' => 'active'],
                ['name' => 'Barrett Hodgson University, Karachi', 'status' => 'active'],
                ['name' => 'Commecs Institute of Business & Emerging Sciences, Karachi', 'status' => 'active'],
                ['name' => 'Dadabhoy Institute of Higher Education,Karachi', 'status' => 'active'],
                ['name' => 'DHA Suffa University, Karachi', 'status' => 'active'],
                ['name' => 'Greenwich University, Karachi', 'status' => 'active'],
                ['name' => 'Hamdard University, Karachi', 'status' => 'active'],
                ['name' => 'Habib University, Karachi', 'status' => 'active'],
                ['name' => 'Indus University, Karachi
', 'status' => 'active'],
                ['name' => 'Indus Valley School of Art and Architecture, Karachi', 'status' => 'active'],
                ['name' => 'Institute of Business Management, Karachi', 'status' => 'active'],
                ['name' => 'ILMA University (Formerly Institute of Business and Technology), Karachi', 'status' => 'active'],
                ['name' => 'Iqra University, Karachi', 'status' => 'active'],
                ['name' => 'Isra University, Hyderabad', 'status' => 'active'],
                ['name' => 'Jinnah University for Women, Karachi', 'status' => 'active'],
                ['name' => 'Karachi Institute of Economics & Technology, Karachi', 'status' => 'active'],
                ['name' => 'KASB Institute of Technology, Karachi', 'status' => 'active'],
                ['name' => 'Karachi School for Business & Leadership, Karachi', 'status' => 'active'],
                ['name' => '', 'status' => 'active'],
                ['name' => '', 'status' => 'active'],
                ['name' => '', 'status' => 'active'],

                      ['name' => '', 'status' => 'active'],
                ['name' => 'Muhammad Ali Jinnah University, Karachi', 'status' => 'active'],
                ['name' => 'Newport Institute of Communications & Economics, Karachi', 'status' => 'active'],
                ['name' => 'Preston Institute of Management, Science and Technology, Karachi', 'status' => 'active'],
                ['name' => 'Preston University, Karachi', 'status' => 'active'],
                ['name' => 'Shaheed Zulfikar Ali Bhutto Institute of Science & Technology (SZABIST), Karachi', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto City University, Karachi', 'status' => 'active'],
                ['name' => 'Sir Syed University of Engineering & Technology, Karachi', 'status' => 'active'],
                ['name' => 'Sindh Institute of Medical Sciences, Karachi', 'status' => 'active'],
                ['name' => 'Sindh Institute of Management and Technology, Karachi', 'status' => 'active'],
                ['name' => 'Textile Institute of Pakistan, Karachi', 'status' => 'active'],
                ['name' => 'Nazeer Hussian University, Karachi', 'status' => 'active'],
                ['name' => 'Zia-ud-Din University, Karachi', 'status' => 'active'],
                ['name' => 'Shaheed Benazir Bhutto Dewan University, Karachi', 'status' => 'active'],
                ['name' => 'Sohail University, Karachi', 'status' => 'active'],
                ['name' => 'Emaan Institute of Management & Sciences, Karachi', 'status' => 'active'],
                ['name' => 'Abasyn University, Peshawar ', 'status' => 'active'],
                ['name' => 'CECOS University of Information Technology and Emerging Sciences, Peshawar', 'status' => 'active'],
                ['name' => 'City University of Science and Information Technology, Peshawar', 'status' => 'active'],
                ['name' => 'Gandhara University, Peshawar', 'status' => 'active'],
                ['name' => 'Ghulam Ishaq Khan Institute of Engineering Sciences & Technology, Topi', 'status' => 'active'],
                ['name' => 'Iqra National University, Peshawar', 'status' => 'active'],
                ['name' => 'Northern University, Nowshera', 'status' => 'active'],
                ['name' => 'Preston University, Kohat', 'status' => 'active'],
                ['name' => 'Qurtaba University of Science and Information Technology, Dera Ismail Khan', 'status' => 'active'],
                ['name' => 'Sarhad University of Science and Information Technology, Peshawar ', 'status' => 'active'],
                ['name' => 'BRAINS Institute, Peshawar', 'status' => 'active'],
                ['name' => 'Al-Hamd Islamic University, Quetta', 'status' => 'active'],
                ['name' => 'Al-Khair University, AJ&K (Banned for new intake of students w.e.f  Fall, 2016 in all subjects and levels)
', 'status' => 'active'],
                ['name' => 'Mohi-ud-Din Islamic University, AJK ', 'status' => 'active']
               
            ]
        );
    }
}
