<?php

use Illuminate\Database\Seeder;

class CampusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('campuses')->insert([
           [ 'business_school_id' => '7' , 'location' => 'Abbottabad'],
           [ 'business_school_id' => '7' , 'location' => 'Attock'],
           [ 'business_school_id' => '7' , 'location' => 'Lahore'],
           [ 'business_school_id' => '7' , 'location' => 'Wah'],
           [ 'business_school_id' => '7' , 'location' => 'vehari'],
           [ 'business_school_id' => '7' , 'location' => 'sahiwal'],
           [ 'business_school_id' => '9' , 'location' => 'karachi'],
           [ 'business_school_id' => '16' , 'location' => 'Faisalabad'],
           [ 'business_school_id' => '16' , 'location' => 'Lahore'],
           [ 'business_school_id' => '16' , 'location' => 'Peshawar'],
           [ 'business_school_id' => '16' , 'location' => 'Multan'],
           [ 'business_school_id' => '16' , 'location' => 'Karachi'],
           [ 'business_school_id' => '16' , 'location' => 'Hyderabad'],
           [ 'business_school_id' => '16' , 'location' => 'Quetta'],
           [ 'business_school_id' => '13' , 'location' => 'Rawalpindi'],
           [ 'business_school_id' => '6' , 'location' => 'Karachi'],
           [ 'business_school_id' => '6' , 'location' => 'Lahore'],
           [ 'business_school_id' => '27' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '27' , 'location' => 'Rawalpindi'],
           [ 'business_school_id' => '27' , 'location' => 'DG Khan'],
           [ 'business_school_id' => '27' , 'location' => 'Faisalabad'],
           [ 'business_school_id' => '27' , 'location' => 'Gujranwala'],
           [ 'business_school_id' => '27' , 'location' => 'Multan'],
           [ 'business_school_id' => '27' , 'location' => 'Sahiwal'],
           [ 'business_school_id' => '27' , 'location' => 'Badin'],
           [ 'business_school_id' => '27' , 'location' => 'Ghotki'],
           [ 'business_school_id' => '27' , 'location' => 'Karachi'],
           [ 'business_school_id' => '27' , 'location' => 'Pashin'],
           [ 'business_school_id' => '27' , 'location' => 'Peshawar'],
           [ 'business_school_id' => '27' , 'location' => 'Muzaffargarh'],
           [ 'business_school_id' => '27' , 'location' => 'Hyderabad'],
           [ 'business_school_id' => '27' , 'location' => 'Jhelum'],
           [ 'business_school_id' => '216' , 'location' => 'Hunza'],
           [ 'business_school_id' => '216' , 'location' => 'Diamer (Chilas)'],
           [ 'business_school_id' => '216' , 'location' => 'Ghizer'],
           [ 'business_school_id' => '217' , 'location' => 'karachi'],
           [ 'business_school_id' => '10' , 'location' => '​KICSIT Kahauta'],
           [ 'business_school_id' => '10' , 'location' => 'Karachi'],
           [ 'business_school_id' => '51' , 'location' => 'Kalashah Kako'],
           [ 'business_school_id' => '51' , 'location' => 'Faisalabad'],
           [ 'business_school_id' => '51' , 'location' => 'Rachna College,  Gujranwala'],
           [ 'business_school_id' => '51' , 'location' => 'Narrowal'],
           [ 'business_school_id' => '56' , 'location' => 'Gujranwala'],
           [ 'business_school_id' => '56' , 'location' => 'Jehlum '],
           [ 'business_school_id' => '44' , 'location' => 'Jhang'],
           [ 'business_school_id' => '50' , 'location' => 'Okara'],
           [ 'business_school_id' => '50' , 'location' => 'DG Khan'],
           [ 'business_school_id' => '50' , 'location' => 'Faisalabad'],
           [ 'business_school_id' => '50' , 'location' => 'Joharabad'],
           [ 'business_school_id' => '50' , 'location' => 'Multan'],
           [ 'business_school_id' => '50' , 'location' => 'Vehari'],
              [ 'business_school_id' => '50' , 'location' => 'Attock'],
           [ 'business_school_id' => '57' , 'location' => 'Patoki'],
           [ 'business_school_id' => '57' , 'location' => 'Jhang'],
           [ 'business_school_id' => '31' , 'location' => 'Layyah'],
           [ 'business_school_id' => '39' , 'location' => 'Rahim Yar Khan'],
           [ 'business_school_id' => '39' , 'location' => 'Bahawalnagar'],
           [ 'business_school_id' => '52' , 'location' => 'Chakwal'],
           [ 'business_school_id' => '52' , 'location' => 'Toba Tek Singh'],
           [ 'business_school_id' => '52' , 'location' => 'Depalpur'],
           [ 'business_school_id' => '52' , 'location' => 'Burewala'],
           [ 'business_school_id' => '53' , 'location' => 'Lahore'],
           [ 'business_school_id' => '53' , 'location' => 'Sialkot '],
           [ 'business_school_id' => '53' , 'location' => 'Narrowal  '],
           [ 'business_school_id' => '53' , 'location' => 'Rawalpindi'],
           [ 'business_school_id' => '33' , 'location' => 'Layyah'],
           [ 'business_school_id' => '33' , 'location' => 'Sahiwal'],
           [ 'business_school_id' => '55' , 'location' => 'Bhakkar'],
           [ 'business_school_id' => '55' , 'location' => 'Mianwali'],
           [ 'business_school_id' => '55' , 'location' => 'Lahore'],
           [ 'business_school_id' => '55' , 'location' => 'Mandi Bahauddin'],
           [ 'business_school_id' => '55' , 'location' => 'Gujranwala'],
           [ 'business_school_id' => '55' , 'location' => 'Faisalabad (Women)'],
           [ 'business_school_id' => '55' , 'location' => 'Lyallpur'],
           [ 'business_school_id' => '86' , 'location' => 'Mirpur Khas'],
           [ 'business_school_id' => '86' , 'location' => 'Badin'],
           [ 'business_school_id' => '86' , 'location' => 'Dadu'],
           [ 'business_school_id' => '74' , 'location' => 'Khairpur'],
           [ 'business_school_id' => '78' , 'location' => 'Shikarpur'],
           [ 'business_school_id' => '77' , 'location' => 'Larkana'],
           [ 'business_school_id' => '83' , 'location' => 'Naushahro Feroze'],
           [ 'business_school_id' => '81' , 'location' => '​Kandkot'],
           [ 'business_school_id' => '103' , 'location' => 'Abbottabad'],
           [ 'business_school_id' => '103' , 'location' => 'Mardan '],
           [ 'business_school_id' => '103' , 'location' => 'Bannu'],
           [ 'business_school_id' => '103' , 'location' => 'Jalozai'],
           [ 'business_school_id' => '103' , 'location' => 'Kohat'],
           [ 'business_school_id' => '104' , 'location' => 'Wari'],
           [ 'business_school_id' => '108' , 'location' => '​Shangla'],
           [ 'business_school_id' => '100' , 'location' => '​Hangu'],
           [ 'business_school_id' => '95' , 'location' => '​Tank'],
           [ 'business_school_id' => '123' , 'location' => '​Gawadar'],
           [ 'business_school_id' => '17' , 'location' => '​Quetta'],
           [ 'business_school_id' => '121' , 'location' => '​Pishin'],
           [ 'business_school_id' => '121' , 'location' => 'Noshki'],
           [ 'business_school_id' => '121' , 'location' => 'Khuzdar'],
           [ 'business_school_id' => '161' , 'location' => 'Islamabad '],
           [ 'business_school_id' => '161' , 'location' => 'Sargodha'],
           [ 'business_school_id' => '161' , 'location' => 'Gujrat '],
           [ 'business_school_id' => '210' , 'location' => 'Islamabad '],
           [ 'business_school_id' => '210' , 'location' => 'Peshawar '],
           [ 'business_school_id' => '210' , 'location' => 'Lahore '],
           [ 'business_school_id' => '186' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '186' , 'location' => 'Larkana'],
           [ 'business_school_id' => '186' , 'location' => 'Dubai'],
           [ 'business_school_id' => '186' , 'location' => 'Hyderabad'],
           [ 'business_school_id' => '212' , 'location' => 'Ras-Al-Khaimah, UAE (Campus)'],
           [ 'business_school_id' => '212' , 'location' => 'Comwave Institute of Information Technology, F-8 Markaz, Islamabad.'],
           [ 'business_school_id' => '212' , 'location' => 'Comwave Institute of Information Technology, F-8 Markaz, Islamabad.'],
           [ 'business_school_id' => '15' , 'location' => 'National Textile Institute (NTI), Main Park Road, Lane # 7, Chak Shehzad, Islamabad  '],
           [ 'business_school_id' => '212' , 'location' => 'Islamabad Federal College (IFC), Plaza # 154, St. No # 30, I&T Center, G-9/1, Islamabad.'],
           [ 'business_school_id' => '212' , 'location' => 'Abbott Group of Colleges,'],
           [ 'business_school_id' => '212' , 'location' => ' Islamabad Expressway, Near TM CNG Station, Khanapul, Islamabad.'],
           [ 'business_school_id' => '212' , 'location' => 'College of Business & Technologies, Comsats University Road, Mandian, Abbottabad.'],
           [ 'business_school_id' => '212' , 'location' => 'Comwave Institute of Sciences & I.T Opposite New China Market, Near Noor Surgical Hospital, D-Stop, Abbottabad Road, Haripur.'],
           [ 'business_school_id' => '212' , 'location' => 'Abbott Group of Colleges,'],
           [ 'business_school_id' => '212' , 'location' => 'Adjacent Zarai Taraqiati Bank, P.O Jhangi, Mansehra Road, Abbottabad. '],
           [ 'business_school_id' => '212' , 'location' => 'Abbott Group of Colleges,'],
           [ 'business_school_id' => '212' , 'location' => 'Opposite WAPDA Grid Station, Near Dhangri Chowk, Shahra-E-Resham, Mansehra.'],
           [ 'business_school_id' => '212' , 'location' => 'Comwave Institute of Sciences & I.T, Near Sultan Plaza, Supply Area, Mansehra Road, Abbottabad.'],
           [ 'business_school_id' => '212' , 'location' => 'ANSI Institute of Education, Science &Technology (AIMS), Nowshera Road, Mardan.    '],
           [ 'business_school_id' => '212' , 'location' => 'Institute of Education & Management Sciences, University Road, D.I. Khan'],
           [ 'business_school_id' => '212' , 'location' => 'Bannu Institute of Education, Science &Technology (BEST), Kacharey Road, Bannu.'],
           [ 'business_school_id' => '212' , 'location' => 'Al Noor College of Engineering & Technology, Rawalpindi Road, Near Bypass Bridge, Opposite U.E.T Campus, Kohat.'],
           [ 'business_school_id' => '212' , 'location' => 'Swabi Engineering College of Technology (SECT), Ahmadabad, Shah Mansoor, Swabi.'],
           [ 'business_school_id' => '212' , 'location' => 'College of Business & I.T, Khaar Road, Opposite Saddam Petrol Pump, College Colony, Batkhela.'],
           [ 'business_school_id' => '212' , 'location' => 'Chakdara Polytechnic Institute, G.T Road, Amir Abad, Chakdara Distt: Dir (L)'],
           [ 'business_school_id' => '212' , 'location' => 'Dir College of Science & Technology, Saddo, Timergara, Dir Lower.'],
           [ 'business_school_id' => '212' , 'location' => 'Saidu Polytechnic Institute,'],
           [ 'business_school_id' => '212' , 'location' => 'Park Avenue, College Colony, Saidu Sharif, Swat.'],
           [ 'business_school_id' => '212' , 'location' => 'Indus Polytechnic Institute,'],
           [ 'business_school_id' => '212' , 'location' => 'G.T Road, Odigram, Swat.'],
           [ 'business_school_id' => '180' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '180' , 'location' => 'Karachi'],
           [ 'business_school_id' => '179' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '179' , 'location' => 'Karachi'],
           [ 'business_school_id' => '135' , 'location' => 'Lahore'],
           [ 'business_school_id' => '135' , 'location' => 'Karachi'],
           [ 'business_school_id' => '135' , 'location' => 'Peshawar'],
           [ 'business_school_id' => '135' , 'location' => 'Chiniot'],
           [ 'business_school_id' => '203' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '173' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '154' , 'location' => 'Multan'],
           [ 'business_school_id' => '154' , 'location' => 'Bahawalpur'],
           [ 'business_school_id' => '154' , 'location' => 'Rahim Yar Khan'],
           [ 'business_school_id' => '211' , 'location' => 'Peshawar '],
           [ 'business_school_id' => '162' , 'location' => 'Sialkot'],
           [ 'business_school_id' => '136' , 'location' => 'Lahore'],
           [ 'business_school_id' => '136' , 'location' => 'Faisalabad'],
           [ 'business_school_id' => '136' , 'location' => 'Malakand '],
           [ 'business_school_id' => '214' , 'location' => 'Islamabad'],
           [ 'business_school_id' => '172' , 'location' => 'Mauritius'],
           [ 'business_school_id' => '145' , 'location' => 'Sheikhupura'],
           [ 'business_school_id' => '131' , 'location' => 'london'],
           [ 'business_school_id' => '132' , 'location' => '​Sialkot'],
           [ 'business_school_id' => '179' , 'location' => 'Sawat']
         ]);

    }
}
